### ISSUE TITLE
Upvote/downvote a deck of cards

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/api-backend#15]
**Description:**

As a developper, I would like to have an endpoint on the API so users can upvote/downvote deck of cards

**Tasks**

- [x] Create a route on the API to vote for a deck of cards.
- [x] The user must be logged and must have, at least, the right to read in the classroom.
- [x] Each can only vote once

**Requirements:**
- #5 
- #8 
- #10 
- #14
