### ISSUE TITLE
Informations to display classroom

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/api-backend#19]
**Description:**

As a developper, I would like to have an endpoint on the API so any users can see all the classrooms he has acces to.

**Tasks**

- [x] Create a route on the API to show all the classrooms of the user.
- [x] The user must be logged and must have least the right to read the classroom.
- [x] Infomations to display for the classroom : title of classroom, nb of cards, creator, score (upvote - downvote)(see figma)

**Requirements:**
- #5 
- #8
- #10
