### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/api-backend#4]
**Description:**

As a developper, I would like to have an endpoint on the API to create an account.

**Tasks**

- [x] Create a route on the API to create an account
- [x] Verify that both password are the same
- [x] Check that the login is not already used
- [ ] Send mail to confirm email ?
- [x] Store the informations in the DB

**Requirements:**
- none

**Comment by maxscharwath** [comment]
For the email verification we have 3 possibilities:
We can generate a token and store this token in db.

But we can also generate a jwt token to avoid creating a db table.

Or we can just sign the url: [https://docs.adonisjs.com/guides/security/signed-urls#document](https://docs.adonisjs.com/guides/security/signed-urls#document)

I think jwt token is a bit too big to be store in url 

So signing url I think is the best, we can just sign the url like this: 
api/v1/verify/[USER_UUID]

We NEED to sign the url to avoid verification automations!
