### ISSUE TITLE
Edit user password

### ISSUE THREAD

**Issue by Marinlestylo** [StudyStorm/api-backend#7]
**Description:**

As a developper, I would like to have an endpoint on the API to change the password of an user.

**Tasks**

- [x] Create a route on the API to change the password of the user
- [x] Verify that the new password is at least 8 characters long.
- [ ] The user must be logged to change his password.

**Requirements:**
- #5
